### ISSUE TITLE
Using Passless with RegistrationController 

### ISSUE THREAD

**Issue by meredevelopment** [DarkGhostHunter/Passless#10]
Sorry to leave a question as an issue. If there’s a better way to ask please tell me. 

Could you suggest how I might use same Passless emailed token immediately after registration in RegistrationController instead of automatically logging the user in? 

I thought that the `->login` call in the register function would make use of the new driver, but it seems to bypass it. 

Any sample code or explanation appreciated 👍👍👍

L5.8

**Comment by DarkGhostHunter** [comment]
The [LoginNotification](https://github.com/DarkGhostHunter/Passless/blob/master/src/LoginNotification.php) uses a [Temporary Signed Route](https://laravel.com/docs/5.8/urls#signed-urls). The signature is created by the framework itself, there is no token exchange anywhere. You're free to create your own Notification with your own logic to extract the signature.

> I thought that the ->login call in the register function would make use of the new driver, but it seems to bypass it.

You must override the `guard()` method with the guard using Passless in your `RegisterController`. Good catch, I'm gonna add it to the README.md

**Comment by meredevelopment** [comment]
Thanks for the reply, and sorry I've left it so long. I've not been able to get this working yet so please could I have a bit more help? You say: 

> You must override the guard() method with the guard using Passless in your RegisterController

How would I do that? I've attempted to set `$this->guard('web')->login($user);` but it's had no effect. Here's my Auth guards config: 

```
'guards' => [
        'web' => [
            'driver' => 'passless',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
            'hash' => false,
        ],
    ],
```
and here's my 'register' method from my RegisterController:
```
public function register(Request $request)
{
    // Gets validated request data.
    $validated = $this->validator($request->all())->validate();

    event(new Registered($user = $this->create($request->all())));

    $this->guard('web')->login($user); //this is where I've added 'web' as the guard name. 

    return $this->registered($request, $user)
        ?: redirect($this->redirectPath());
}
``` 

If you have time to try this out, and get Laravel registration firing off the email upon login the same way LoginController does, I would be extremely grateful.

**Comment by DarkGhostHunter** [comment]
This method: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Auth/RegistersUsers.php#L41-L49

Show the error log.

**Comment by meredevelopment** [comment]
I don't get any errors, it just doesn't make use of Passless at all. I tried to add the guard() method you mentioned directly to the RegisterController but no change.

I've had a deeper look at how things work, and got it to work by doing an Auth attempt directly. Here's my complete working controller:

```php
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\User;
use App\Member;
use Illuminate\Auth\Events\Registered;
use App\Events\UserCreated;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;
use Illuminate\Http\Request;

class RegisterController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Register Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users as well as their
    | validation and creation. By default this controller uses a trait to
    | provide this functionality without requiring any additional code.
    |
    */

    use RegistersUsers;

    /**
     * Where to redirect users after registration.
     *
     * @var string
     */
    protected $redirectTo = '/wait';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest');
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'memnum' => ['required', 'numeric', 'digits_between:1,10', 'exists:members,mid'],
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return \App\User
     */
    protected function create(array $data)
    {
        return User::create([
            'email' => $data['email'],
        ]);
    }

    /**
     * Handle a registration request for the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function register(Request $request)
    {
        // Gets validated request data.
        $validated = $this->validator($request->all())->validate();

        // Checks if member is migrated to this system. If not passes to old system.
        $member = new Member;
        if (!$member->migrated($validated['memnum']))
        {
            return redirect()->away('http://example.com?' . http_build_query($validated));
        }

        event(new Registered($user = $this->create($request->all())));
        event(new UserCreated($user, $validated['memnum']));

        Auth::attempt($user->only('email'));

        return $this->registered($request, $user)
            ?: redirect($this->redirectPath());
    }
}
```

This is working, but if you think there's a better way, or if this is likely to cause issues, please let me know. If this way is acceptable I could PR the readme if you like?

**Comment by DarkGhostHunter** [comment]
That's weird, it should use Passless. Passless basically overrides one method of the default `StatefulGuard`, so the registration process should not be affected, and that includes the events fired.

Once the user registers, the system should push the email since there should be nothing against the registration process.

**Comment by meredevelopment** [comment]
I'm out of my depth here from a troubleshooting point of view, but I did just test something. 

With the following in RegistrationController:

```
$this->guard()->login($user);
```

The login method being called is [the one in SessionGuard](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Auth/SessionGuard.php#L405-L424). Is that correct?

**Comment by DarkGhostHunter** [comment]
@meredevelopment Yes, since Passless just extends the `SessionGuard` - [it just overrides the `attempt()` method of it](https://github.com/DarkGhostHunter/Passless/blob/master/src/PasslessGuard.php#L26-L52).
