### ISSUE TITLE
Queueable notification error: `Serialization of 'Closure' is not allowed`

### ISSUE THREAD

**Issue by spacenate** [DarkGhostHunter/Passless#3]
Framework: Laravel 5.8
PHP: 7.3.3

When the `passless` Guard driver's `attempt()` method is called, I get the following server error:

![Screen Shot 2019-03-30 at 9 56 20 PM](https://user-images.githubusercontent.com/11892841/55284554-b0240200-5336-11e9-94d7-56ec82f4ef38.png)

Some research turned up a [StackOverflow question](https://stackoverflow.com/questions/43643626/laravel-queueable-notification-errors-serialization-of-closure-is-not-allowed) with the same error. It appears storing a reference to type-hinted dependencies is not okay in a Queueable Notification.

**Comment by DarkGhostHunter** [comment]
Fixed by #4.
