### ISSUE TITLE
Add to instruction

### ISSUE THREAD

**Issue by sauliuslt** [DarkGhostHunter/Passless#6]
Hi,
for less experienced coders i suggest to add instruction that in order for this to function you need to override validateLogin function so it doesn't expect password. In your instruction it says only delete password field from login.blade.php

Add to LoginController.php

`use Illuminate\Http\Request;`

   ```
public function validateLogin(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email|exists:users',]);

    }
```

**Comment by DarkGhostHunter** [comment]
Done, ty.
