### ISSUE TITLE
Dude - where's your website?

### ISSUE THREAD

**Issue by achieveforum** [DarkGhostHunter/Passless#8]
@DarkGhostHunter Thanks for your work on this. It looks like a well thought out implementation for passwordless auth. I'm going to plug it in to a site I'm working on now and check it out.

FYI: Your website [http://italobc.com](http://italobc.com) linked in github is not responding. Do you have another website address or could you send me your contact info? I may have some coding / project / work for you, in the near future, if you are interested?

Thanks,

Robert

**Comment by DarkGhostHunter** [comment]
> FYI: Your website http://italobc.com linked in github is not responding. 

Checked that out, I hit the limit on domains per server. No fix in the short term.

> Do you have another website address or could you send me your contact info? I may have some coding / project / work for you, in the near future, if you are interested?

Thanks, but currently I'm with my hands full with [this mammoth](https://github.com/DarkGhostHunter/TransbankApi).
