### ISSUE TITLE
Unable to publish config with 'vendor:publish'

### ISSUE THREAD

**Issue by meredevelopment** [DarkGhostHunter/Passless#9]
Laravel 5.8.28
Passless 2.0.1
PHP 7.2.18

When I run `php artisan vendor:publish --provider=DarkGhostHunter\Passless\PasslessServiceProvider` I get the message "Publishing complete" but no file is created/copied into my config dir.

I've attempted to clear cache, and dump autoload, and I'm told that: 
`Discovered Package: darkghosthunter/passless`.

Please let me know if I can test anything and provide more info. Thanks!

**Comment by DarkGhostHunter** [comment]
Can replicate. Investigating...

**Comment by DarkGhostHunter** [comment]
Fixed: double quotes [are mandatory](https://laravel.com/docs/5.8/artisan#tinker). Running the following should be fine:

`php artisan vendor:publish --provider="DarkGhostHunter\Passless\PasslessServiceProvider"`
